irqchip: irq-gic: Fix checkpatch errors
Fixes the following errors:
ERROR: do not initialise statics to 0 or NULL
ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Sachin Kamat <sachin.kamat@linaro.org>
Signed-off-by: Olof Johansson <olof@lixom.net>

(cherry picked from commit 46f101df788b38fafa08e85dcbf85d3bff6c1ea3)
Signed-off-by: Shinya Kuribayashi <shinya.kuribayashi.px@renesas.com>